### ISSUE TITLE
Wrong dates for Frontend Conference Zürich

### ISSUE THREAD

**Issue by sareg0** [nimzco/confs.tech#10]
Hey, here is a conference that has the wrong dates listed.

Frontend Conference Zurich
Zurich, Switzerland - Oct, 1st
https://frontendconf.ch/

Listed as 1st October, but below are the dates listed on their site: 31 AUG - 1 SEP 2017

```json
  {
    "name": "Frontend Conference Zurich",
    "url": "https://frontendconf.ch/",
    "startDate": "2017-08-31",
    "endtDate": "2017-09-01",
    "city": "Zürich",
    "country": "Switzerland",
    "cspUrl": "",
    "twitter": "@frontendconfch",
  }
```

**Comment by nimzco** [comment]
Oh nice catch, thanks! 👍🏼
