### ISSUE TITLE
TechBash 2017

### ISSUE THREAD

**Issue by alvinashcraft** [nimzco/confs.tech#6]
Hey, here is a conference that is missing from the list.

```json
  {
    "name": "TechBash 2017",
    "url": "https://www.techbash.com/",
    "startDate": "2017-10-04",
    "endtDate": "2017-10-06",
    "city": "Pocono Manor, PA",
    "country": "USA",
    "cspUrl": "",
    "twitter": "@techbash",
  }
```

**Comment by nimzco** [comment]
Hey Alvin, I'm not sure where to add this since it's neither really Ruby or JavaScript.
Is it general tech? If so I won't be able to add it to a specific track.

**Comment by alvinashcraft** [comment]
Hi Nima. The conference as a whole is general dev, but I thought since there are enough JavaScript sessions for a JS dev to fill most of their 3 days with relevant content that it might fit. I understand if you need to reject this. Thanks for considering!

**Comment by nimzco** [comment]
Oh I see. I think that makes sense then, I'll add this 👍
